stages:
  - lint

lint-and-typecheck:
  stage: lint
  image: astral/uv:bookworm-slim   # generic uv image
  script:
    - cd backend
    - uv sync --locked
    - uv run ruff check .
    - uv run ruff format --check .
    - uv run pyright