"""create attendances table

Revision ID: 0d8f3a19392e
Revises: 9b74f7678f40
Create Date: 2026-07-24 21:12:42.378172

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d8f3a19392e"
down_revision: str | Sequence[str] | None = "9b74f7678f40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "present", "paid_leave", "unpaid_leave", "half_day", name="attendance_status_enum"
            ),
            nullable=False,
        ),
        sa.Column(
            "overtime_hours", sa.Numeric(precision=6, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "date", name="uq_attendance_employee_date"),
    )
    op.create_index(op.f("ix_attendances_date"), "attendances", ["date"], unique=False)
    op.create_index(
        op.f("ix_attendances_employee_id"), "attendances", ["employee_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attendances_employee_id"), table_name="attendances")
    op.drop_index(op.f("ix_attendances_date"), table_name="attendances")
    op.drop_table("attendances")
    # ### end Alembic commands ###
