"""create payroll tables

Revision ID: 9721a7b3ec06
Revises: 0d8f3a19392e
Create Date: 2026-07-26 19:48:46.341722

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9721a7b3ec06"
down_revision: str | Sequence[str] | None = "0d8f3a19392e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payroll_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("draft", "finalized", name="payroll_status_enum"), nullable=False
        ),
        sa.Column("total_amount_due", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_warning", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "year", "month", name="uq_payroll_runs_business_period"),
    )
    op.create_index(
        op.f("ix_payroll_runs_business_id"), "payroll_runs", ["business_id"], unique=False
    )
    op.create_table(
        "payroll_line_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payroll_run_id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("employee_name", sa.String(length=255), nullable=False),
        sa.Column("salary_type", sa.String(length=20), nullable=False),
        sa.Column("base_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("divisor_policy_used", sa.String(length=20), nullable=True),
        sa.Column("overtime_multiplier_used", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("working_hours_used", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("present_days", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("half_days", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("paid_leave_days", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("unpaid_leave_days", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("holiday_days", sa.Integer(), nullable=False),
        sa.Column("weekly_off_days_count", sa.Integer(), nullable=False),
        sa.Column("overtime_hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("earned_salary", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("overtime_pay", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_additions", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_deductions", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("net_payable", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status", sa.Enum("draft", "finalized", name="payroll_status_enum"), nullable=False
        ),
        sa.Column("paid_via", sa.String(length=50), nullable=True),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["payroll_run_id"], ["payroll_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payroll_line_items_business_id"),
        "payroll_line_items",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_line_items_employee_id"),
        "payroll_line_items",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_line_items_payroll_run_id"),
        "payroll_line_items",
        ["payroll_run_id"],
        unique=False,
    )
    op.create_table(
        "payroll_warnings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payroll_line_item_id", sa.UUID(), nullable=False),
        sa.Column(
            "warning_type",
            sa.Enum("missing_attendance", name="payroll_warning_type_enum"),
            nullable=False,
        ),
        sa.Column("affected_dates", postgresql.ARRAY(sa.Date()), nullable=False),
        sa.Column("message", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payroll_line_item_id"], ["payroll_line_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payroll_warnings_payroll_line_item_id"),
        "payroll_warnings",
        ["payroll_line_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payroll_warnings_payroll_line_item_id"), table_name="payroll_warnings")
    op.drop_table("payroll_warnings")
    op.drop_index(op.f("ix_payroll_line_items_payroll_run_id"), table_name="payroll_line_items")
    op.drop_index(op.f("ix_payroll_line_items_employee_id"), table_name="payroll_line_items")
    op.drop_index(op.f("ix_payroll_line_items_business_id"), table_name="payroll_line_items")
    op.drop_table("payroll_line_items")
    op.drop_index(op.f("ix_payroll_runs_business_id"), table_name="payroll_runs")
    op.drop_table("payroll_runs")
    # ### end Alembic commands ###
