"""fix numeric precisions in database

Revision ID: 9b74f7678f40
Revises: 6a39e55c0c44
Create Date: 2026-07-17 18:37:21.291369

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b74f7678f40'
down_revision: str | Sequence[str] | None = '6a39e55c0c44'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'default_overtime_multiplier',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=False)
    op.alter_column('businesses', 'default_working_hours',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=False)
    op.add_column('employees', sa.Column('weekly_off_days', sa.ARRAY(sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='weekday_enum')), nullable=False))
    op.alter_column('employees', 'overtime_multiplier',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('2.0'))
    op.alter_column('employees', 'working_hours',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=False)
    op.drop_column('employees', 'default_weekly_off_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('default_weekly_off_days', postgresql.ARRAY(postgresql.ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='weekday_enum')), autoincrement=False, nullable=False))
    op.alter_column('employees', 'working_hours',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=False)
    op.alter_column('employees', 'overtime_multiplier',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=False,
               existing_server_default=sa.text('2.0'))
    op.drop_column('employees', 'weekly_off_days')
    op.alter_column('businesses', 'default_working_hours',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=False)
    op.alter_column('businesses', 'default_overtime_multiplier',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###
