"""create employees table

Revision ID: b9fe7e0e5bb1
Revises: d744f006560e
Create Date: 2026-07-16 01:58:51.845305

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9fe7e0e5bb1"
down_revision: str | Sequence[str] | None = "d744f006560e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=15), nullable=True),
        sa.Column("designation", sa.String(length=100), nullable=True),
        sa.Column(
            "salary_type",
            sa.Enum("monthly", "daily", "hourly", name="salary_type_enum"),
            nullable=False,
        ),
        sa.Column("base_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "overtime_multiplier",
            sa.Numeric(precision=3, scale=1),
            server_default="2.0",
            nullable=False,
        ),
        sa.Column(
            "default_weekly_off_days",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "monday",
                    "tuesday",
                    "wednesday",
                    "thursday",
                    "friday",
                    "saturday",
                    "sunday",
                    name="weekday_enum",
                    create_type=False,
                ),
            ),
            nullable=False,
        ),
        sa.Column("working_hours", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("joining_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "name", name="uq_employee_business_name"),
    )
    op.create_index(op.f("ix_employees_business_id"), "employees", ["business_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employees_business_id"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
