"""create business table

Revision ID: bc7b780cda80
Revises: f1e496ecff72
Create Date: 2026-07-08 19:46:31.938833

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc7b780cda80"
down_revision: str | Sequence[str] | None = "f1e496ecff72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "businesses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column(
            "divisor_policy",
            sa.Enum("26", "30", "calendar", name="divisor_policy_enum"),
            nullable=False,
        ),
        sa.Column("default_overtime_multiplier", sa.Numeric(precision=3, scale=1), nullable=False),
        sa.Column(
            "default_weekly_off_days",
            postgresql.ARRAY(
                sa.Enum(
                    "monday",
                    "tuesday",
                    "wednesday",
                    "thursday",
                    "friday",
                    "saturday",
                    "sunday",
                    name="weekday_enum",
                )
            ),
            nullable=False,
        ),
        sa.Column("default_working_hours", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "slug", name="uq_business_owner_slug"),
    )
    op.create_index(op.f("ix_businesses_id"), "businesses", ["id"], unique=False)
    op.create_index(op.f("ix_businesses_slug"), "businesses", ["slug"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_businesses_slug"), table_name="businesses")
    op.drop_index(op.f("ix_businesses_id"), table_name="businesses")
    op.drop_table("businesses")
    # ### end Alembic commands ###
