"""create holidays table

Revision ID: d744f006560e
Revises: bc7b780cda80
Create Date: 2026-07-08 21:02:49.014401

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d744f006560e"
down_revision: str | Sequence[str] | None = "bc7b780cda80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holidays",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("holiday_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("holiday_type", sa.String(length=10), server_default="custom", nullable=False),
        sa.Column("is_paid", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "holiday_date", name="uq_holidays_biz_date"),
    )
    op.create_index(op.f("ix_holidays_business_id"), "holidays", ["business_id"], unique=False)
    op.create_index(op.f("ix_holidays_holiday_date"), "holidays", ["holiday_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_holidays_holiday_date"), table_name="holidays")
    op.drop_index(op.f("ix_holidays_business_id"), table_name="holidays")
    op.drop_table("holidays")
    # ### end Alembic commands ###
